import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
    en:{
        AppName:"JobLamp",
        Login:"Login",
        SIGNUP:"SIGN UP",
        EmailAddress:"Email Address",
        Password:"Password",
        ForgotPass:"Forgot Password?",
        ForgotPassText:"Forgot Password",
        DontHaveAccount:"Don't have an account?",
        TopRatedTW:"Top rated task workers",
        EnterValiEmail:"Please enter valid email address.",
        EnterPass:"Please enter password.",
        EnterFirstName:"Please enter first name.",
        EnterLastName:"Please enter last name.",
        EnterMobile:"Please enter mobile number.",
        EnterAptmt:"Please enter Apartment.",
        FirstName:"First Name",
        LastName:"Last Name",
        MobileNumber:"Mobile Number",
        EnterStreet:"Please enter Street Name.",
        EnterCountry:"Please choose Country.",
        EnterState:"Please choose State.",
        EnterCity:"Please choose City.",
        EnterPincode:"Please enter Pincode.",
        Country:"Country",
        State:"State",
        City:"City",
        TaskGiver:"Task Giver",
        TaskWorker:"Task Worker",
        RegisterAs:"Register as:",
        SignUp:"Sign Up",
        AlreadyHaveAcc:"Already have an account?",
        LOGIN:"LOGIN",
        CurrentJobs:"Current Jobs",
        AppliedJobs:"Applied Jobs",
        CompletedJobd:"Completed Jobs",
        TotalEarnings:"Total Earnings",
        PostedJobs:"Posted Jobs",
        PastJobs:"Past Jobs",
        ViewByCategory:"Jobs By Category",
        ViewAll:"View All",
        RecentJobs:"Recent Jobs",
        AboutUs:"About Us",
        ApplicationDetails:"Application Details",
        BidAmount:"Bid Amount:",
        Hire:"Hire",
        EnterBiddAmount:"Please enter Bid Amount.",
        EnterCoverText:"Please enter Cover Letter text.",
        ApplyJob:"Apply Job",
        BiddAmountUSD:"Bid Amount (USD)",
        CoverLetter:"Cover Letter",
        Apply:"Apply",
        Jobs:"Jobs",
        Categories:"Categories",
        EnterOldPass:"Please enter old password.",
        EnterNewPass:"Please enter new password.",
        PassConfPassNotMatch:"Password and Confirm Password does not match.",
        PassChanged:"Password changed successfully.",
        ResetPass:"Reset Password",
        CreateNewPass:"Create new password",
        PleaseEnterCode:"Please enter the code that has been sent to you via email",
        Code:"Code",
        NewPass:"New Password",
        RetypeNewPass:"Re-type New Password",
        ChoosePhoto:"Choose Photo",
        ChooseFile:"Choose File",
        Cancel:"Cancel",
        Chat:"Chat",
        Chats:"Chats",
        EnterDeliveryDetails:"Please enter delivery details",
        DeliverJob:"Deliver Job",
        Deliveries:"Deliveries",
        DeliveryNotes:"Delivery Notes",
        Attachment:"Attachment",
        Deliver:"Deliver",
        ApproveJob:'Approve Job',
        RequestModification:'Request Modification',
        Dashboard:"Home",
        MyJobs:"My Jobs",
        Profile:"Profile",
        Notifications:"Notifications",
        Settings:"Settings",
        Logout:"Logout",
        EditProfile:"Edit Profile",
        ApartmentBuilding:"Apartment/Building",
        Street:"Street",
        Pincode:"Pincode",
        AboutMe:"About Me",
        Save:"Save",
        EULA:"End User License Agreement",
        EnterRegisterEmail:"Enter your email to receive password reset code",
        Submit:"Submit",
        Contact:"Contact",
        JobApplications:"Job Applications",
        JobDetails:"Job Details",
        JobInformation:"Job Information",
        JobFrom:"Job From",
        StartDate:"Start Date",
        EndDate:"End Date",
        MinPrice:"Min Price",
        MaxPrice:"Max Price",
        Description:"Description",
        Location:"Location",
        FeedBackTW:"Feedback For Task Worker",
        FeedbackTG:"Feedback for Task Giver",
        Message:"Message",
        ViewDelivery:"View All Deliveries",
        ViewJobApplications:"View Job Applications",
        ApplyforJob:"Apply for Job",
        ViewAllDeliveries:"View All Deliveries",
        ProvideFeedback:"Provide Feedback",
        Price:"Price",
        ClearAll:"Clear All",
        English:"English",
        Spanish:"Spanish",
        French:"French",
        German:"German",
        Portuguese:"Portuguese",
        Russian:"Russian",
        ChangeLanguage:"Change Language",
        Posted:"Posted",
        Applied:"Applied",
        Active:"Active",
        Delivered:"Delivered",
        Past:"Past",
        Completed:"Completed",
        PostNewJob:"Post a new Job",
        Payment:"Payment",
        EnterTitle:"Please enter title.",
        EnterCategory:"Please select category.",
        EnterStartDate:"Please select start date.",
        EnterEndDate:"Please select end date.",
        EnterMinBudget:"Please enter miniimum budget.",
        EnterDesc:"Please enter job description.",
        PostJob:"Post a Job",
        Done:"Done",
        JobTitle:"Job Title",
        MinPriceUsd:"Min Price (USD)",
        MaxPriceUsd:"Max Price (USD)",
        PrivacyPolicy:"Privacy Policy",
        Edit:"Edit",
        Delete:"Delete",
        Reviews:"Reviews",
        Upcoming:"Upcoming",
        CurrentlyIn:"Currently In",
        Skills:"Skills",
        UpdateSkills:"Update your skills",
        SubmittedDocs:"Submitted Docs",
        Choose:"Choose",
        SupportedDocPDF:"Supported document format is pdf only",
        UpdateYourDocs:"Update your docs",
        EnterFeedback:"Please enter yoour feedback",
        Feedback:"Feedback",
        WriteFeedback:"Write Feedback",
        EnterCodeReceived:"Please enter code you have received via email.",
        Search:"Search",
        ChangeAppLang:"Change App Language",
        TermsConditions:"Terms and Conditions",
        Category:"Category",
        SelectOneParam:"Please select at least one parameter",
        NoJobFound:"No job found for the given parameters",
        Address:"Address",
        FailedToRetriveProfile:"Failed to retrieve profile details",
        DocsUploaded:"Documents uploaded successfully",
        DocsUploadedFailed:"Failed to upload documents",
        Current:"Current",
        Document1:"Document1",
        Document2:"Document2",
        Document3:"Document3",
        SelectQueryType:"Please select query type",
        QueryText:"Please enter few words about your query",
        QuerySubmitted:"We have received your query, our support team member will reach you soon.",
        ContactUs:"Contact Us",
        EnterQuery:"Enter your query",
        GeneralQuery:'General Query',
        Dispute:'Dispute',
        PaymentIssue:'Payment Issue',
        Other:'Other',
        AnyTaskToPost:'Do you have any task to post?',
        TermsPrivacy:"I agree to the JobLamp's",
        AcceptTermsPrivacy:"Please accept Terms & Conditions and Privacy Policy",
        AppliedForJob:"You have successfully applied for the job",
        AboutJobLamp:'We help you to find a professional to do any job. We are available worldwide, multilingual. We offer monthly lottery money prizes to make you happy. Job Lamp has professionals in many fields like IT, computer design, desc jobs to repair and construction, courier services, cleaning and housekeeping, events and promotions, repair and installation machines, legal aid, pet sitting and many more.We provide an opportunity to the professionals to explore their skills worldwide and providing service to task givers to get their job done by professional of their choice.',
        AboutLotto:'We offer monthly lotto prizes to our Basic and VIP account subscribers to make them happy working with us. We offer 15 lotto prizes every month. 1st Place 300 USD (1 winner), 2nd Place 75 USD (4 winners), 3rd place 20 USD (10 winners). We offer quarterly prizes of 500 USD to our VIP subscribers.Our annual lotto for VIP customers will include a 1st prize place of a brand new car delivered to your door. Our annual lotto for Basic Account holders will include 4 first prize places of an electronic scooter delivered to your door.The draw will be live broadcasted on our YouTube channel and will be 100% random with no bias.Be a subscribed member and get an opportunity to win monthly lotto prizes.',
        NoJobFound:'No jobs found',
        Subscriptions:'Subscriptions',
        VisitWeb:'Visit Our Website',
        FreeAccount:'Free Account',
        FeaturesOf:'Features Of',
        SubFeatures:'No free jobs to apply \nPay per job application',
        month:'month',
        year:'year',
        BasicAccount:'Basic Account',
        FeaturesBasic:'You can apply up to 15 jobs for free \nPay 2 USD per job after 15 jobs applications \nYou can apply for monthly lotto prizes \nUpload up to 3 portfolios \nChoose up to 3 categories \nChoose up to 3 skills',
        VipAccount:'VIP Account',
        FeatureVIP:'Can apply for unlimited jobs \nBy default eligible for monthly lotto prizes \nCan apply for putting their profile on top \nUpload up to 10 portfolios \nChoose any number of categories \nChoose any number of skills',
        Skip:'Skip',
        BirthDate:'Birth Date',
        ChooseBirthDate:'Please choose Birth Date',
        ViewPortFolio:'View Portfolio',
        PortFolio:'Portfolio',
        UploadPortfolio:'Upload Portfolio',
        ClickButton:'Click below button to upload',
        NoPortFolio:'You do not have any portfolio yet',
        Title:'Title',
        ChooseType:'Choose Type',
        MaxPhotoFileSize:'Please upload photo of size within 5 MB',
        MaxVideoFileSize:'Please upload video of size within 30 MB',
        ChoosePhoto:'Choose Photo',
        ChooseVideo:'Choose Video',
        AddLink:'Add Link',
        UpdateCategories:'Update Categories',
        UpgradePlanForSkill:'You can not choose more skills. Upgrade to VIP plan to choose unlimited skills',
        UpgradePlanForCategories:'You can not choose more categories. Upgrade to VIP plan to choose unlimited categories',
        FreeAccountHolderPortFolio:'As a free account holder you can not upload any portfolio',
        BasicAccountHolderPortFolio:'As a basic account holder you can upload upto 3 portfolios',
        VIPAccountHolderPortFolio:'As a VIP account holder you can upload upto 10 portfolios',
        WithdrawalAmount:'Please enter amount to withdraw',
        WithdrawalRequest:'Withdrawal Request',
        Amount:'Amount',
        SubscribeLine:'Click on subscribe button from the below mentioned subscription plans to any of them.',
        Subscribe:'Subscribe',
        SelectMonthlyYearly:'Please select subscription duration either monthly or yearly'

    },
    es:{
        AppName:"JobLamp",
        Login:"Acceso",
        SIGNUP:"INSCRIBIRSE",
        EmailAddress:"Dirección de correo electrónico",
        Password:"Contraseña",
        ForgotPass:"Mot de passe oublié?",
        DontHaveAccount:"¿No tienes una cuenta?",
        TopRatedTW:"Trabajadores de tareas mejor calificados",
        EnterValiEmail:"Introduce una dirección de correo electrónico válida.",
        EnterPass:"Introduzca la contraseña.",
        EnterFirstName:"Introduce el nombre.",
        EnterLastName:"Please enter last name.",
        EnterMobile:"Introduce el apellido.",
        EnterAptmt:"Por favor, introduzca apartamento.",
        FirstName:"Primer nombre",
        LastName:"Apellido",
        MobileNumber:"Número de móvil",
        EnterStreet:"Introduce el nombre de la calle.",
        EnterCountry:"Por favor, elija País.",
        EnterState:"Elija Estado.",
        EnterCity:"Por favor, elija Ciudad.",
        EnterPincode:"Introduce pincode.",
        Country:"País",
        State:"estado",
        City:"Cuidad",
        TaskGiver:"Dador de tareas",
        TaskWorker:"Trabajador de tareas",
        RegisterAs:"Regístrese como:",
        SignUp:"Suscríbete",
        AlreadyHaveAcc:"¿Ya tienes una cuenta?",
        LOGIN:"Iniciar sesión",
        CurrentJobs:"Trabajos actuales",
        AppliedJobs:"Trabajos aplicados",
        CompletedJobd:"Trabajos completados",
        TotalEarnings:"Ganancias totales",
        PostedJobs:"Trabajos publicados",
        PastJobs:"Trabajos pasados",
        ViewByCategory:"Trabajos por categoría",
        ViewAll:"Ver todo",
        RecentJobs:"Trabajos recientes",
        AboutUs:"Sobre nosotros",
        ApplicationDetails:"Detalles de la aplicación",
        BidAmount:"Importe de la puja:",
        Hire:"alquilar",
        EnterBiddAmount:"Introduce el importe de la puja.",
        EnterCoverText:"Ingrese por favor el texto de la carta de cubierta.",
        ApplyJob:"Aplicar trabajo",
        BiddAmountUSD:"Importe de la puja (USD)",
        CoverLetter:"carta de presentación",
        Apply:"Aplique",
        Jobs:"empleos",
        Categories:"Categorías",
        EnterOldPass:"Introduzca una contraseña antigua.",
        EnterNewPass:"Introduzca una nueva contraseña.",
        PassConfPassNotMatch:"La contraseña y la contraseña de confirmación no coinciden.",
        PassChanged:"La contraseña se ha cambiado correctamente.",
        ResetPass:"Restablecer contraseña",
        CreateNewPass:"Crear nueva contraseña",
        PleaseEnterCode:"Introduce el código que se te ha enviado por correo electrónico",
        Code:"Código",
        NewPass:"Nueva contraseña",
        RetypeNewPass:"Vuelva a escribir Nueva contraseña",
        ChoosePhoto:"Elija la foto",
        ChooseFile:"Elegir archivo",
        Cancel:"Cancelar",
        Chat:"Chat",
        Chats:"Chats",
        EnterDeliveryDetails:"Introduce los detalles de la entrega",
        DeliverJob:"Entregar trabajo",
        DeliveryNotes:"Notas de entrega",
        Attachment:"archivo adjunto",
        Deliver:"entregar",
        ApproveJob:'Approve Job',
        RequestModification:'Request Modification',
        Dashboard:"salpicadero",
        MyJobs:"Mis trabajos",
        Profile:"perfil",
        Notifications:"notificaciones",
        Settings:"Configuración",
        Logout:"Cerrar sesión",
        EditProfile:"Editar perfil",
        ApartmentBuilding:"Departamento/Edificio",
        Street:"Callete",
        Pincode:"Código pin",
        AboutMe:"Acerca de mí",
        Save:"Guardar",
        EULA:"Contrato de licencia de usuario final",
        EnterRegisterEmail:"Ingrese su correo electrónico para recibir el código de restablecimiento de contraseña",
        Submit:"EnviarEnviar",
        Contact:"Contacto",
        JobApplications:"Solicitudes de empleo",
        JobDetails:"Detalles del trabajo",
        JobInformation:"Información del trabajo",
        JobFrom:"Trabajo de",
        StartDate:"fecha de inicio",
        EndDate:"fecha final",
        MinPrice:"Precio mínimo",
        MaxPrice:"Precio máximo",
        Description:"descripción",
        Location:"ubicaci",
        FeedBackTW:"Comentarios para el trabajador de tareas",
        FeedbackTG:"Comentarios para el dador de tareas",
        Message:"mesaje",
        ViewDelivery:"Ver entrega",
        ViewJobApplications:"Ver solicitudes de empleo",
        ApplyforJob:"Solicitar empleo",
        ProvideFeedback:"Proporcionar comentarios",
        Price:"Presio",
        ClearAll:"Borrar todo",
        English:"Inglés",
        Spanish:"Español",
        French:"Francesa",
        German:"Alemán",
        Portuguese:"Portuguesa",
        Russian:"Rusa",
        ChangeLanguage:"Cambiar idioma",
        Posted:"Escritos",
        Applied:"aplicado",
        Active:"activo",
        Delivered:"entregado",
        ApproveJob:'Aprobar trabajo',
        RequestModification:'Solicitar modificación',
        Past:"Past",
        Completed:"completado",
        PostNewJob:"Publicar un nuevo trabajo",
        Payment:"pago",
        EnterTitle:"Introduce el título.",
        EnterCategory:"Seleccione la categoría.",
        EnterStartDate:"Seleccione la fecha de inicio.",
        EnterEndDate:"Seleccione la fecha de finalización.",
        EnterMinBudget:"Introduce un presupuesto mínimo.",
        EnterDesc:"Introduce la descripción del puesto de trabajo.",
        PostJob:"Publicar un trabajo",
        Done:"hecho",
        JobTitle:"Cargo",
        MinPriceUsd:"Precio mínimo (USD)",
        MaxPriceUsd:"Precio máximo (USD)",
        PrivacyPolicy:"Política de Privacidad",
        Edit:"Editar",
        Delete:"Borrar",
        Reviews:"Comentarios",
        Upcoming:"próximo",
        CurrentlyIn:"Actualmente en",
        Skills:"HABILIDADES",
        UpdateSkills:"Actualiza tus habilidades",
        SubmittedDocs:"Documentos enviados",
        Choose:"eligen",
        SupportedDocPDF:"El formato de documento compatible es solo pdf",
        UpdateYourDocs:"Actualiza tus documentos",
        EnterFeedback:"Introduce tus comentarios sobre yoour",
        Feedback:"retroalimentación",
        WriteFeedback:"Escribir comentarios",
        EnterCodeReceived:"Introduce el código que has recibido por correo electrónico.",
        Search:"Buscar",
        ChangeAppLang:"Cambiar el idioma de la aplicación",
        TermsConditions:"Términos y Condiciones",        
        Category:"categoria",
        SelectOneParam:"Seleccione al menos un parámetro",
        NoJobFound:"No se ha encontrado ningún trabajo para los parámetros dados",
        Address:"abordan",
        FailedToRetriveProfile:"No se pudieron recuperar los detalles del perfil",
        DocsUploaded:"Documentos cargados correctamente",
        DocsUploadedFailed:"No se pudieron cargar documentos",
        Current:"actual",
        Document1:"Documento1",
        Document2:"Documento2",
        Document3:"Documento3",
        SelectQueryType:"Seleccione el tipo de consulta",
        QueryText:"Introduce algunas palabras sobre tu consulta",
        QuerySubmitted:"Hemos recibido su consulta, nuestro miembro del equipo de soporte se pondrá en contacto con usted pronto.",
        ContactUs:"Contáctanos",
        EnterQuery:"Introduzca su consulta",
        GeneralQuery:'Consulta general',
        Dispute:'disputa',
        PaymentIssue:'Problema de pago',
        Other:'Demas',
        AnyTaskToPost:'¿Tienes alguna tarea que publicar?',
        TermsPrivacy:"Estoy de acuerdo con el JobLamp de",
        AcceptTermsPrivacy:"Por favor, acepte los Términos y Condiciones y la Política de Privacidad",
        AppliedForJob:"Ha solicitado correctamente el trabajo",
        AboutJobLamp:"Te ayudamos a encontrar un profesional para realizar cualquier trabajo. Estamos disponibles en todo el mundo, multilingües. Ofrecemos premios de lotería mensuales para hacerle feliz. Job Lamp cuenta con profesionales en muchos campos como TI, diseño de computadoras, trabajos de desc para reparación y construcción, servicios de mensajería, limpieza y limpieza, eventos y promociones, reparación e instalación de máquinas, asistencia legal, cuidado de mascotas y muchos más.Brindamos una oportunidad a los profesionales de explorar sus habilidades en todo el mundo y brindar servicio a los encargados de tareas para que el profesional de su elección realice su trabajo.",
        AboutLotto:"Ofrecemos premios de lotería mensuales a nuestros suscriptores de cuentas Basic y VIP para hacerlos felices trabajando con nosotros. Ofrecemos 15 premios de lotería cada mes. 1er lugar 300 USD (1 ganador), 2do lugar 75 USD (4 ganadores), 3er lugar 20 USD (10 ganadores). Ofrecemos premios trimestrales de 500 USD a nuestros suscriptores VIP. Nuestra lotería anual para clientes VIP incluirá un primer lugar de premio de un automóvil nuevo entregado en su puerta. Nuestra lotería anual para titulares de cuentas básicas incluirá 4 lugares para el primer premio de un scooter electrónico entregado en su puerta. El sorteo se transmitirá en vivo en nuestro canal de YouTube y será 100% aleatorio sin sesgos. Sea un miembro suscrito y obtenga una oportunidad para ganar premios de lotería mensuales.",
        NoJobFound:'No se encontraron trabajos',
        Subscriptions:'Suscripciones',
        VisitWeb:'Visite nuestro sitio web',
        FreeAccount:'Cuenta gratis',
        FeaturesOf:'Caracteristicas de',
        SubFeatures:'No hay trabajos gratuitos para postularse \nPaga por solicitud de trabajo',
        month:'mes',
        year:'año',
        BasicAccount:'Cuenta básica',
        FeaturesBasic:'Puedes postular hasta 15 trabajos gratis \ nPaga 2 USD por trabajo después de 15 solicitudes de trabajo \ nPuedes solicitar premios de lotería mensuales \ nSube hasta 3 carteras \ nElige hasta 3 categorías \ nElige hasta 3 habilidades',
        VipAccount:'Cuenta VIP',
        FeatureVIP:'Puede postularse para trabajos ilimitados \ nDe forma predeterminada, es elegible para premios de lotería mensuales \ nPuede postularse para poner su perfil en la parte superior \ nSubir hasta 10 carteras \ nElija cualquier cantidad de categorías \ nElija cualquier cantidad de habilidades',
        Skip:'Saltar',
        BirthDate:'Fecha de nacimiento',
        ChooseBirthDate:'Elija la fecha de nacimiento',
        ViewPortFolio:'Ver portafolio',
        PortFolio:'portafolio',
        UploadPortfolio:'Subir portafolio',
        ClickButton:'Haga clic en el botón de abajo para cargar',
        NoPortFolio:'Aún no tienes ninguna cartera',
        Title:'Título',
        ChooseType:'Elija el tipo',
        MaxPhotoFileSize:'Sube una foto de tamaño dentro de los 5 MB',
        MaxVideoFileSize:'Sube un video de un tamaño inferior a 30 MB',
        ChoosePhoto:'Escoge una foto',
        ChooseVideo:'Elija video',
        AddLink:'Añadir enlace',
        UpdateCategories:'Actualizar categorías',
        UpgradePlanForSkill:'No puedes elegir más habilidades. Actualice al plan VIP para elegir habilidades ilimitadas',
        UpgradePlanForCategories:'No puedes elegir más categorías. Actualice al plan VIP para elegir categorías ilimitadas',
        FreeAccountHolderPortFolio:'Como titular de una cuenta gratuita, no puede cargar ningún portafolio',
        BasicAccountHolderPortFolio:'Como titular de una cuenta básica, puede cargar hasta 3 carteras',
        VIPAccountHolderPortFolio:'Como titular de una cuenta VIP, puede cargar hasta 10 carteras',
        WithdrawalAmount:'Ingrese el monto a retirar',
        WithdrawalRequest:'Solicitud de Retiro',
        Amount:'Monto',
        SubscribeLine:'Haga clic en el botón de suscripción de los planes de suscripción mencionados a continuación para cualquiera de ellos.',
        Subscribe:'Suscribir',
        SelectMonthlyYearly:'Seleccione la duración de la suscripción mensual o anual'
    },
    fr:{
        AppName:"JobLamp",
        Login:"Connexion",
        SIGNUP:"S'INSCRIRE",
        EmailAddress:"Adresse e-mail",
        Password:"Mot de passe",
        ForgotPass:"¿Has olvidado tu contraseña?",
        DontHaveAccount:"Vous n'avez pas de compte?",
        TopRatedTW:"Travailleurs les mieux notés",
        EnterValiEmail:"Veuillez saisir une adresse e-mail valide.",
        EnterPass:"Entrez le mot de passe.",
        EnterFirstName:"Veuillez saisir votre prénom.",
        EnterLastName:"Veuillez saisir votre nom de famille.",
        EnterMobile:"Veuillez saisir le numéro de téléphone mobile.",
        EnterAptmt:"Veuillez saisir Apartment(en) .",
        FirstName:"Prénom",
        LastName:"Nom de famille",
        MobileNumber:"Numéro de téléphone portable",
        EnterStreet:"Entrez le nom de la rue.",
        EnterCountry:"Veuillez choisir Pays.",
        EnterState:"Veuillez choisir État.",
        EnterCity:"Veuillez choisir Ville.",
        EnterPincode:"Entrez pincode.",
        Country:"Pays",
        State:"d'etat",
        City:"Ville",
        TaskGiver:"Donneur de tâches",
        TaskWorker:"Travailleur de tâche",
        RegisterAs:"Inscrivez-vous en tant que :",
        SignUp:"Inscrivez-vous",
        AlreadyHaveAcc:"Vous avez déjà un compte ?",
        LOGIN:"S'IDENTIFIER",
        CurrentJobs:"Emplois actuels",
        AppliedJobs:"Emplois appliqués",
        CompletedJobd:"Travaux terminés",
        TotalEarnings:"Gains totaux",
        PostedJobs:"Emplois affichés",
        PastJobs:"Emplois antérieurs",
        ViewByCategory:"Emplois par catégorie",
        ViewAll:"Afficher tout",
        RecentJobs:"Emplois récents",
        AboutUs:"Qui sommes-nous",
        ApplicationDetails:"Détails de la demande",
        BidAmount:"Montant de l’enchère :",
        Hire:"louer",
        EnterBiddAmount:"Saisissez le montant de l’enchère.",
        EnterCoverText:"Veuillez saisir le texte de la lettre d’accompagnement.",
        ApplyJob:"Postuler à l’emploi",
        BiddAmountUSD:"Montant de l’enchère (USD)",
        CoverLetter:"Lettre de motivation",
        Apply:"Postuler",
        Jobs:"Emplois",
        Categories:"Catégories",
        EnterOldPass:"Veuillez saisir l'ancien mot de passe.",
        EnterNewPass:"Entrez un nouveau mot de passe.",
        PassConfPassNotMatch:"Le mot de passe et confirmer le mot de passe ne correspondent pas.",
        PassChanged:"Mot de passe modifié avec succès.",
        ResetPass:"Réinitialiser le mot de passe",
        CreateNewPass:"Créer un nouveau mot de passe",
        PleaseEnterCode:"Veuillez saisir le code qui vous a été envoyé par e-mail",
        Code:"Code",
        NewPass:"Nouveau mot de passe",
        RetypeNewPass:"Re-taper nouveau mot de passe",
        ChoosePhoto:"Choisissez une photo",
        ChooseFile:"Choisissez un fichier",
        Cancel:"Supprimer",
        Chat:"Chatter",
        Chats:"Chats (chats)",
        EnterDeliveryDetails:"Veuillez saisir les détails de la livraison",
        DeliverJob:"Livrer le travail",
        DeliveryNotes:"Notes de livraison",
        Attachment:"attachement",
        Deliver:"Livrer",
        Dashboard:"Accueil",
        MyJobs:"Mes emplois",
        Profile:"profil",
        Notifications:"Notifications",
        Settings:"Paramètres",
        Logout:"Déconnexion",
        EditProfile:"Modifier votre profil",
        ApartmentBuilding:"Appartement/Bâtiment",
        Street:"street",
        Pincode:"Code pin",
        AboutMe:"À propos de Moi",
        Save:"Garder",
        EULA:"Contrat de licence utilisateur final",
        EnterRegisterEmail:"Entrez votre e-mail pour recevoir le code de réinitialisation du mot de passe",
        Submit:"Envoyez",
        Contact:"Contacter",
        JobApplications:"Demandes d’emploi",
        JobDetails:"Détails de l’emploi",
        JobInformation:"Informations sur l’emploi",
        JobFrom:"Emploi à partir de",
        StartDate:"Date de début",
        EndDate:"Date de fin",
        MinPrice:"Prix minimum",
        MaxPrice:"Prix max",
        Description:"la description",
        Location:"emplacement",
        FeedBackTW:"Commentaires pour le travailleur de tâche",
        FeedbackTG:"Commentaires pour Task Giver",
        Message:"Message",
        ViewDelivery:"Afficher la livraison",
        ViewJobApplications:"Afficher les demandes d’emploi",
        ApplyforJob:"Postulez pour un emploi",
        ProvideFeedback:"Fournir des commentaires",
        Price:"Prix",
        ClearAll:"Effacer tout",
        English:"Anglais",
        Spanish:"L'espagnol",
        French:"français",
        German:"allemand",
        Portuguese:"Portugais",
        Russian:"Russe",
        ChangeLanguage:"Changer la langue",
        Posted:"Posté",
        Applied:"appliqué",
        Active:"actif",
        Delivered:"livré",
        ApproveJob:'Approuver le travail',
        RequestModification:'Demander une modification',
        Past:"past",
        Completed:"terminé",
        PostNewJob:"Publier un nouvel emploi",
        Payment:"Paiement",
        EnterTitle:"Veuillez saisir le titre.",
        EnterCategory:"Veuillez sélectionner la catégorie.",
        EnterStartDate:"Veuillez sélectionner la date de début.",
        EnterEndDate:"Veuillez sélectionner la date de fin.",
        EnterMinBudget:"Veuillez saisir le budget miniimum.",
        EnterDesc:"Veuillez saisir la description du poste.",
        PostJob:"Publier un emploi",
        Done:"Fait",
        JobTitle:"Titre du poste",
        MinPriceUsd:"Prix minimum (USD)",
        MaxPriceUsd:"Prix maximum (USD)",
        PrivacyPolicy:"Politique de confidentialité",
        Edit:"edit",
        Delete:"Retour",
        Reviews:"Avis",
        Upcoming:"prochain",
        CurrentlyIn:"Actuellement en",
        Skills:"compétences",
        UpdateSkills:"Mettez à jour vos compétences",
        SubmittedDocs:"Documents soumis",
        Choose:"choisissons",
        SupportedDocPDF:"Le format de document pris en charge est au format pdf uniquement",
        UpdateYourDocs:"Mettre à jour vos documents",
        EnterFeedback:"S’il vous plaît entrer yoour commentaires",
        Feedback:"commentaires",
        WriteFeedback:"Écrire des commentaires",
        EnterCodeReceived:"Veuillez saisir le code que vous avez reçu par e-mail.",
        Search:"Rechercher",
        ChangeAppLang:"Modifier la langue de l’application",
        TermsConditions:"Termes et Conditions",
        Category:"categorie",
        SelectOneParam:"Veuillez sélectionner au moins un paramètre",
        NoJobFound:"Aucun travail trouvé pour les paramètres donnés",
        Address:"adress",
        FailedToRetriveProfile:"Impossible de récupérer les détails du profil",
        DocsUploaded:"Documents téléchargés avec succès",
        DocsUploadedFailed:"Echec du téléchargement des documents",
        Current:"actuelle",
        Document1:"Document1",
        Document2:"Document2",
        Document3:"Document3",
        SelectQueryType:"Sélectionnez le type de requête",
        QueryText:"Entrez quelques mots sur votre requête",
        QuerySubmitted:"Nous avons reçu votre demande, notre membre de l’équipe d’assistance vous contactera bientôt.",
        ContactUs:"Contactez-nous",
        EnterQuery:"Entrez votre requête",
        GeneralQuery:'Requête générale',
        Dispute:'dispute',
        PaymentIssue:'Problème de paiement',
        Other:'Autres',
        AnyTaskToPost:'Avez-vous une tâche à publier?',
        TermsPrivacy:"J’accepte les offres d’emploi de JobLamp",
        AcceptTermsPrivacy:"Veuillez accepter les termes et conditions et la politique de confidentialité",
        AppliedForJob:"Vous avez postulé avec succès pour le travail",
        AboutJobLamp:"Nous vous aidons à trouver un professionnel pour faire n'importe quel travail. Nous sommes disponibles dans le monde entier, multilingues. Nous offrons des prix de loterie mensuels pour vous rendre heureux. Job Lamp compte des professionnels dans de nombreux domaines tels que l'informatique, la conception informatique, les travaux de réparation et de construction, les services de messagerie, le nettoyage et l'entretien ménager, les événements et les promotions, les machines de réparation et d'installation, l'aide juridique, la garde d'animaux et bien d'autres.Nous offrons aux professionnels l'opportunité d'explorer leurs compétences dans le monde entier et de fournir un service aux donneurs d'ordre pour que leur travail soit fait par le professionnel de leur choix.",
        AboutLotto:"Nous offrons des prix de loto mensuels à nos abonnés aux comptes Basic et VIP pour les rendre heureux de travailler avec nous. Nous offrons 15 prix de loto chaque mois. 1ère place 300 USD (1 gagnant), 2e place 75 USD (4 gagnants), 3e place 20 USD (10 gagnants). Nous offrons des prix trimestriels de 500 USD à nos abonnés VIP. Notre loto annuel pour les clients VIP comprendra une 1ère place de prix d'une toute nouvelle voiture livrée à votre porte. Notre loto annuel pour les titulaires d'un compte de base comprendra 4 places pour le premier prix d'un scooter électronique livré à votre porte. Le tirage sera diffusé en direct sur notre chaîne YouTube et sera 100% aléatoire, sans parti pris. Soyez un membre abonné et obtenez une opportunité pour gagner des prix de loto mensuels.",
        NoJobFound:'Aucun emploi trouvé',
        Subscriptions:'Abonnements',
        VisitWeb:'Visitez notre site Internet',
        FreeAccount:'Compte gratuit',
        FeaturesOf:'Les caractéristiques de',
        SubFeatures:"Pas d'offres d'emploi gratuites à appliquer \nPayez par demande d'emploi",
        month:'mois',
        year:'an',
        BasicAccount:'Compte de base',
        FeaturesBasic:"Vous pouvez postuler gratuitement jusqu'à 15 offres d'emploi \nPayez 2 USD par offre d'emploi après 15 demandes d'emploi \nVous pouvez postuler pour des prix de loto mensuels \nTéléchargez jusqu'à 3 portfolios \nChoisissez jusqu'à 3 catégories\nChoisissez jusqu'à 3 compétences",
        VipAccount:'Compte VIP',
        FeatureVIP:"Peut postuler pour un nombre illimité d'emplois \nÉligible par défaut aux prix du loto mensuel \nPeut postuler pour mettre son profil en haut \nTélécharger jusqu'à 10 portefeuilles \nChoisissez n'importe quel nombre de catégories \nChoisissez n'importe quel nombre de compétences",
        Skip:'Sauter',
        BirthDate:'Date de naissance',
        ChooseBirthDate:'Veuillez choisir la date de naissance',
        ViewPortFolio:'Voir le portefeuille',
        PortFolio:'Portefeuille',
        UploadPortfolio:'Télécharger le portfolio',
        ClickButton:'Cliquez sur le bouton ci-dessous pour télécharger',
        NoPortFolio:"Vous n'avez pas encore de portefeuille",
        Title:'Titre',
        ChooseType:'Choisissez le type',
        MaxPhotoFileSize:"Veuillez télécharger une photo de taille inférieure à 5 Mo",
        MaxVideoFileSize:"Veuillez télécharger une vidéo d'une taille inférieure à 30 Mo",
        ChoosePhoto:'Choisissez la photo',
        ChooseVideo:'Choisissez la vidéo',
        AddLink:'Ajouter un lien',
        UpdateCategories:'Mettre à jour les catégories',
        UpgradePlanForSkill:'Vous ne pouvez pas choisir plus de compétences. Passez au plan VIP pour choisir des compétences illimitées',
        UpgradePlanForCategories:'Vous ne pouvez pas choisir plus de catégories. Passez au plan VIP pour choisir des catégories illimitées',
        FreeAccountHolderPortFolio:"En tant que titulaire de compte gratuit, vous ne pouvez télécharger aucun portefeuille",
        BasicAccountHolderPortFolio:"En tant que titulaire de compte de base, vous pouvez télécharger jusqu'à 3 portefeuilles",
        VIPAccountHolderPortFolio:"En tant que titulaire d'un compte VIP, vous pouvez télécharger jusqu'à 10 portefeuilles",
        WithdrawalAmount:'Veuillez saisir le montant à retirer',
        WithdrawalRequest:'Demande de retrait',
        Amount:'Montante',
        SubscribeLine:'Cliquez sur le bouton dabonnement parmi les plans dabonnement mentionnés ci-dessous pour lun dentre eux.',
        Subscribe:'Sabonner',
        SelectMonthlyYearly:"Veuillez sélectionner la durée de l'abonnement mensuelle ou annuelle"
    },
    de:{
        AppName:"JobLamp",
        Login:"Anmeldung",
        SIGNUP:"ANMELDEN",
        EmailAddress:"E-Mail-Addresse",
        Password:"Passwort",
        ForgotPass:"Passwort vergessen?",
        DontHaveAccount:"Sie haben noch keinen Account?",
        TopRatedTW:"Bestbewertete Task Worker",
        EnterValiEmail:"Bitte geben Sie eine gültige E-Mail-Adresse ein.",
        EnterPass:"Bitte geben Sie das Kennwort ein.",
        EnterFirstName:"Bitte geben Sie den Vornamen ein.",
        EnterLastName:"Bitte geben Sie den Nachnamen ein.",
        EnterMobile:"Bitte geben Sie die Handynummer ein.",
        EnterAptmt:"Bitte geben Sie das Apartment ein.",
        FirstName:"Vorname",
        LastName:"Nachname",
        MobileNumber:"Handynummer",
        EnterStreet:"Bitte geben Sie den Straßennamen ein.",
        EnterCountry:"Bitte wählen Sie Land.",
        EnterState:"Bitte wählen Sie Staat.",
        EnterCity:"Bitte wählen Sie Stadt.",
        EnterPincode:"Bitte geben Sie Pincode ein.",
        Country:"Land",
        State:"Staatsan",
        City:"Stadt",
        TaskGiver:"Aufgabengeber",
        TaskWorker:"Aufgabenarbeiter",
        RegisterAs:"Registrieren Sie sich als:",
        SignUp:"Anmelden",
        AlreadyHaveAcc:"Sie haben bereits ein Konto?",
        LOGIN:"einloggen",
        CurrentJobs:"Aktuelle Jobs",
        AppliedJobs:"Angewandte Jobs",
        CompletedJobd:"Abgeschlossene Jobs",
        TotalEarnings:"Gesamtergebnis",
        PostedJobs:"Posted Jobs",
        PastJobs:"Vergangene Jobs",
        ViewByCategory:"Jobs nach Kategorie",
        ViewAll:"Alle anzeigen",
        RecentJobs:"Aktuelle Jobs",
        AboutUs:"Über uns",
        ApplicationDetails:"Anwendungsdetails",
        BidAmount:"Gebotsbetrag:",
        Hire:"Mieten",
        EnterBiddAmount:"Bitte geben Sie Gebotsbetrag ein.",
        EnterCoverText:"Bitte geben Sie den Anschreiben-Text ein.",
        ApplyJob:"Bewerben Job",
        BiddAmountUSD:"Gebotsbetrag (USD)",
        CoverLetter:"Anschreiben",
        Apply:"Bewirb",
        Jobs:"Jobs",
        Categories:"Kategorien",
        EnterOldPass:"Bitte geben Sie das alte Passwort ein.",
        EnterNewPass:"Geben Sie ein neues Passwort ein.",
        PassConfPassNotMatch:"Kennwort und Kennwort bestätigen stimmt nicht überein.",
        PassChanged:"Kennwort wurde erfolgreich geändert.",
        ResetPass:"Zurücksetzen des Kennworts",
        CreateNewPass:"Neues Kennwort erstellen",
        PleaseEnterCode:"Bitte geben Sie den Code ein, der Ihnen per E-Mail zugesandt wurde",
        Code:"Code",
        NewPass:"Neues Passwort",
        RetypeNewPass:"Neues Kennwort neu eingeben",
        ChoosePhoto:"Wählen Sie Foto",
        ChooseFile:"Wählen Sie Datei",
        Cancel:"Kündige",
        Chat:"Chat",
        Chats:"Chats",
        EnterDeliveryDetails:"Bitte geben Sie Lieferdetails ein",
        DeliverJob:"Lieferauftrag",
        DeliveryNotes:"Lieferhinweise",
        Attachment:"Anhang",
        Deliver:"Liefern",
        Dashboard:"Instrumententafel",
        MyJobs:"Meine Jobs",
        Profile:"Profil",
        Notifications:"Benachrichtigungen",
        Settings:"Einstellungen",
        Logout:"Abmelden",
        EditProfile:"Bearbeitungsprofil",
        ApartmentBuilding:"Wohnung/Gebäude",
        Street:"strabe",
        Pincode:"Geheimzahl",
        AboutMe:"Über mich",
        Save:"speichern",
        EULA:"Endbenutzer-Lizenzvertrag",
        EnterRegisterEmail:"Geben Sie Ihre E-Mail-Adresse ein, um den Passwort-Reset-Code zu erhalten",
        Submit:"einreichen",
        Contact:"Kontakt",
        JobApplications:"Bewerbungen",
        JobDetails:"Jobdetails",
        JobInformation:"Jobinformationen",
        JobFrom:"Job Von",
        StartDate:"Startdatum",
        EndDate:"Enddatum",
        MinPrice:"Min Preis",
        MaxPrice:"Max Preis",
        Description:"Bezeichnung",
        Location:"einsatzort",
        FeedBackTW:"Feedback für Task Worker",
        FeedbackTG:"Feedback für Task Giver",
        Message:"Nachricht",
        ViewDelivery:"Lieferung anzeigen",
        ViewJobApplications:"Stellenbewerbungen anzeigen",
        ApplyforJob:"Bewerben Sie sich für Job",
        ProvideFeedback:"Feedback geben",
        Price:"Preis",
        ClearAll:"Alle löschen",
        English:"Englisch",
        Spanish:"Spanisch",
        French:"Französisch",
        German:"Deutsch",
        Portuguese:"Portugiesisch",
        Russian:"Russisch",
        ChangeLanguage:"Sprache ändern",
        Posted:"verschickt",
        Applied:"Angewendet",
        Active:"Wirk",
        Delivered:"Zugestellt",
        ApproveJob:'Job genehmigen',
        RequestModification:'Änderung anfordern',
        Past:"Vergan",
        Completed:"abgeschlossene",
        PostNewJob:"Posten eines neuen Jobs",
        Payment:"Zahlung",
        EnterTitle:"Bitte geben Sie den Titel ein.",
        EnterCategory:"Bitte wählen Sie Kategorie aus.",
        EnterStartDate:"Wählen Sie das Startdatum aus.",
        EnterEndDate:"Wählen Sie das Enddatum aus.",
        EnterMinBudget:"Geben Sie das Mindestbudget ein.",
        EnterDesc:"Bitte geben Sie die Stellenbeschreibung ein.",
        PostJob:"Posten eines Jobs",
        Done:"Fertig",
        JobTitle:"Stellentitel",
        MinPriceUsd:"Min Preis (USD)",
        MaxPriceUsd:"Max Preis (USD)",
        PrivacyPolicy:"Datenschutzregeln",
        Edit:"Bearbeiten",
        Delete:"Löschen",
        Reviews:"Bewertungen",
        Upcoming:"Bevorstehende",
        CurrentlyIn:"Derzeit in",
        Skills:"Fähigkeiten",
        UpdateSkills:"Aktualisieren Sie Ihre Fähigkeiten",
        SubmittedDocs:"Eingereichte Dokumente",
        Choose:"Wähl",
        SupportedDocPDF:"Das unterstützte Dokumentformat ist nur pdf",
        UpdateYourDocs:"Aktualisieren Sie Ihre Dokumente",
        EnterFeedback:"Bitte geben Sie yoour Feedback ein",
        Feedback:"Ruckmeldung",
        WriteFeedback:"Feedback schreiben",
        EnterCodeReceived:"Bitte geben Sie den Code ein, den Sie per E-Mail erhalten haben.",
        Search:"Suche",
        ChangeAppLang:"App-Sprache ändern",
        TermsConditions:"Allgemeine Geschäftsbedingungen",
        Category:"Kategorie",
        SelectOneParam:"Bitte wählen Sie mindestens einen Parameter aus",
        NoJobFound:"Für die angegebenen Parameter wurde kein Auftrag gefunden.",
        Address:"Adresse",
        FailedToRetriveProfile:"Fehler beim Abrufen von Profildetails",
        DocsUploaded:"Erfolgreich hochgeladene Dokumente",
        DocsUploadedFailed:"Fehler beim Hochladen von Dokumenten",
        Current:"Laufende",
        Document1:"Dokument1",
        Document2:"Dokument2",
        Document3:"Dokument3",
        SelectQueryType:"Bitte wählen Sie Deneanfragetyp aus",
        QueryText:"Bitte geben Sie ein paar Worte zu Ihrer Anfrage ein",
        QuerySubmitted:"Wir haben Ihre Anfrage erhalten, unser Support-Teammitglied wird Sie bald erreichen.",
        ContactUs:"Kontakt",
        EnterQuery:"Geben Sie Ihre Abfrage ein",
        GeneralQuery:'Allgemeine Abfrage',
        Dispute:'Streit',
        PaymentIssue:'Zahlungsproblem',
        Other:'Andere',
        AnyTaskToPost:'Haben Sie eine Aufgabe zu buchen?',
        TermsPrivacy:"Ich stimme der JobLamp zu",
        AcceptTermsPrivacy:"Bitte akzeptieren Sie Allgemeine Geschäftsbedingungen und Datenschutzerklärung",
        AppliedForJob:"Sie haben sich erfolgreich für den Auftrag beworben",
        AboutJobLamp:'Wir helfen Ihnen, einen Fachmann für jede Aufgabe zu finden. Wir sind weltweit, mehrsprachig verfügbar. Wir bieten monatliche Lotteriegeldpreise an, um Sie glücklich zu machen. Job Lamp hat Fachleute in vielen Bereichen wie IT, Computerdesign, Schreibtischarbeiten für Reparatur und Bau, Kurierdienste, Reinigung und Hauswirtschaft, Veranstaltungen und Werbeaktionen, Reparatur- und Installationsmaschinen, Rechtshilfe, Haustierbetreuung und vieles mehr.Wir bieten Fachleuten die Möglichkeit, ihre Fähigkeiten weltweit zu erkunden und bieten Aufgabengebern einen Service, damit sie ihre Arbeit von einem Fachmann ihrer Wahl erledigen lassen.',
        AboutLotto:"Wir bieten unseren Abonnenten von Basic- und VIP-Konten monatliche Lottopreise an, damit sie glücklich mit uns arbeiten. Wir bieten jeden Monat 15 Lottogewinne an. 1. Platz 300 USD (1 Gewinner), 2. Platz 75 USD (4 Gewinner), 3. Platz 20 USD (10 Gewinner). Wir bieten unseren VIP-Abonnenten vierteljährliche Preise von 500 USD. Unser jährliches Lotto für VIP-Kunden beinhaltet einen 1. Preisplatz eines brandneuen Autos, das an Ihre Tür geliefert wird. Unser jährliches Lotto für Inhaber eines Basiskontos umfasst 4 Hauptgewinnplätze eines elektronischen Rollers, der an Ihre Tür geliefert wird. Die Ziehung wird live auf unserem YouTube-Kanal übertragen und erfolgt zu 100% zufällig und ohne Voreingenommenheit. Seien Sie ein abonniertes Mitglied und erhalten Sie eine Gelegenheit um monatliche Lottopreise zu gewinnen.",
        NoJobFound:'Keine Jobs gefunden',
        Subscriptions:'Abonnements',
        VisitWeb:'Besuche unsere Webseite',
        FreeAccount:'Kostenloser Account',
        FeaturesOf:'Merkmale',
        SubFeatures:'Keine kostenlosen Stellen zur Bewerbung \nZahlung pro Bewerbung',
        month:'Monat',
        year:'Jahr',
        BasicAccount:'Basiskonto',
        FeaturesBasic:'Sie können sich bis zu 15 Jobs kostenlos bewerben \nZahlen Sie 2 USD pro Job nach 15 Bewerbungen \nSie können sich für monatliche Lottogewinne bewerben \nLaden Sie bis zu 3 Portfolios hoch \nWählen Sie bis zu 3 Kategorien \nWählen Sie bis zu 3 Fähigkeiten',
        VipAccount:'VIP-Konto',
        FeatureVIP:'Kann sich für unbegrenzte Jobs bewerben \nStandardmäßig berechtigt für monatliche Lottopreise \nKann sich bewerben, um sein Profil an die Spitze zu setzen \nLaden Sie bis zu 10 Portfolios hoch \nWählen Sie eine beliebige Anzahl von Kategorien \nWählen Sie eine beliebige Anzahl von Fähigkeiten',
        Skip:'Überspringen',
        BirthDate:'Geburtstag',
        ChooseBirthDate:'Bitte wählen Sie das Geburtsdatum',
        ViewPortFolio:'Portfolio ansehen',
        PortFolio:'Portfolio',
        UploadPortfolio:'Portfolio hochladen',
        ClickButton:'Klicken Sie zum Hochladen auf die Schaltfläche unten',
        NoPortFolio:'Sie haben noch kein Portfolio',
        Title:'Titel',
        ChooseType:'Typ wählen',
        MaxPhotoFileSize:'Bitte laden Sie ein Foto mit einer Größe von 5 MB hoch',
        MaxVideoFileSize:"Bitte laden Sie ein Video mit einer Größe von weniger als 30 MB hoch",
        ChoosePhoto:'Wähle ein Foto aus',
        ChooseVideo:'Wählen Sie Video',
        AddLink:'Link hinzufügen',
        UpdateCategories:'Kategorien aktualisieren',
        UpgradePlanForSkill:'Sie können nicht mehr Fähigkeiten auswählen. Upgrade auf VIP-Plan, um unbegrenzte Fähigkeiten zu wählen',
        UpgradePlanForCategories:'Sie können keine weiteren Kategorien auswählen. Upgrade auf VIP-Plan, um unbegrenzte Kategorien zu wählen',
        FreeAccountHolderPortFolio:'Als kostenloser Kontoinhaber können Sie kein Portfolio hochladen',
        BasicAccountHolderPortFolio:'Als Basiskontoinhaber können Sie bis zu 3 Portfolios hochladen',
        VIPAccountHolderPortFolio:'Als VIP-Kontoinhaber können Sie bis zu 10 Portfolios hochladen',
        WithdrawalAmount:'Bitte geben Sie den abzuhebenden Betrag ein',
        WithdrawalRequest:'Auszahlungsantrag',
        Amount:'Menge',
        SubscribeLine:'Klicken Sie auf die Schaltfläche Abonnieren von den unten genannten Abonnementplänen für einen von ihnen.',
        Subscribe:'Abonnieren',
        SelectMonthlyYearly:'Bitte wählen Sie die Abonnementdauer entweder monatlich oder jährlich'
    },
    pt:{
        AppName:"JobLamp",
        Login:"Conecte-se",
        SIGNUP:"INSCREVER-SE",
        EmailAddress:"Endereço de e-mail",
        Password:"Senha",
        ForgotPass:"Esqueceu a senha?",
        DontHaveAccount:"Não tem conta?",
        TopRatedTW:"Trabalhadores da tarefa com melhor classificação",
        EnterValiEmail:"Por favor, insira endereço de e-mail válido.",
        EnterPass:"Por favor, digite a senha.",
        EnterFirstName:"Por favor, digite o primeiro nome.",
        EnterLastName:"Por favor, digite o sobrenome.",
        EnterMobile:"Por favor, digite o número do celular.",
        EnterAptmt:"Por favor, entre no apartamento.",
        FirstName:"Primeiro nome",
        LastName:"Último Nome",
        MobileNumber:"Número móvel",
        EnterStreet:"Por favor, digite Street Name.",
        EnterCountry:"Por favor, escolha o País.",
        EnterState:"Por favor, escolha o Estado.",
        EnterCity:"Por favor, escolha a cidade.",
        EnterPincode:"Por favor, digite Pincode.",
        Country:"País",
        State:"estado",
        City:"Cidade",
        TaskGiver:"Doador de Tarefas",
        TaskWorker:"Trabalhador de tarefas",
        RegisterAs:"Registre-se como:",
        SignUp:"Inscrição",
        AlreadyHaveAcc:"Já tem uma conta?",
        LOGIN:"login",
        CurrentJobs:"Empregos atuais",
        AppliedJobs:"Empregos Aplicados",
        CompletedJobd:"Trabalhos concluídos",
        TotalEarnings:"Lucro Total",
        PostedJobs:"Empregos postados",
        PastJobs:"Empregos passados",
        ViewByCategory:"Empregos por categoria",
        ViewAll:"Ver tudo",
        RecentJobs:"Empregos recentes",
        AboutUs:"Quem somos",
        ApplicationDetails:"Detalhes do aplicativo",
        BidAmount:"Valor do lance:",
        Hire:"alugar",
        EnterBiddAmount:"Por favor, digite o Valor do Lance.",
        EnterCoverText:"Por favor, digite o texto da Carta de Apresentação.",
        ApplyJob:"Candidatar-se a trabalho",
        BiddAmountUSD:"Valor da oferta (USD)",
        CoverLetter:"Carta de apresentação",
        Apply:"aplicar",
        Jobs:"Empregos",
        Categories:"Categorias",
        EnterOldPass:"Por favor, digite senha antiga.",
        EnterNewPass:"Por favor, digite nova senha.",
        PassConfPassNotMatch:"Senha e Confirmação de Senha não correspondem.",
        PassChanged:"A senha mudou com sucesso.",
        ResetPass:"Redefinir senha",
        CreateNewPass:"Criar nova senha",
        PleaseEnterCode:"Por favor, digite o código que foi enviado para você por e-mail",
        Code:"Código",
        NewPass:"Nova Senha",
        RetypeNewPass:"Reestilegrafar nova senha",
        ChoosePhoto:"Escolha foto",
        ChooseFile:"Escolha arquivo",
        Cancel:"Cancelar",
        Chat:"bate papo",
        Chats:"Conversas",
        EnterDeliveryDetails:"Por favor, digite os detalhes da entrega",
        DeliverJob:"Entregar trabalho",
        DeliveryNotes:"Notas de entrega",
        Attachment:"anexo",
        Deliver:"entregar",
        Dashboard:"painel",
        MyJobs:"Meus Trabalhos",
        Profile:"perfile",
        Notifications:"Notificações",
        Settings:"settings",
        Logout:"Sair",
        EditProfile:"Editar Perfil",
        ApartmentBuilding:"Apartamento/Prédio",
        Street:"rua",
        Pincode:"Pincode",
        AboutMe:"Sobre Mim",
        Save:"Guardar",
        EULA:"Contrato de licença do usuário final",
        EnterRegisterEmail:"Digite seu e-mail para receber código de redefinição de senha",
        Submit:"Enviar",
        Contact:"Contacto",
        JobApplications:"Aplicações de Emprego",
        JobDetails:"Aplicações de Emprego",
        JobInformation:"Informações sobre trabalho",
        JobFrom:"Trabalho de",
        StartDate:"Data de início",
        EndDate:"Data de término",
        MinPrice:"Preço min",
        MaxPrice:"Preço máximo",
        Description:"descricao",
        Location:"localização",
        FeedBackTW:"Feedback para trabalhador de tarefas",
        FeedbackTG:"Feedback para doador de tarefas",
        Message:"Mensagem",
        ViewDelivery:"Exibir entrega",
        ViewJobApplications:"Exibir aplicações de emprego",
        ApplyforJob:"Inscreva-se para o trabalho",
        ProvideFeedback:"Fornecer feedback",
        Price:"preço",
        ClearAll:"Apagar tudo",
        English:"Inglês",
        Spanish:"Espanhol",
        French:"Francês",
        German:"Alemão",
        Portuguese:"Português",
        Russian:"Russo",
        ChangeLanguage:"Alterar Idioma",
        Posted:"Postado",
        Applied:"aplicado",
        Active:"ativo",
        Delivered:"Entregado",
        ApproveJob:'Aprovar Trabalho',
        RequestModification:'Solicitar Modificação',
        Past:"Past",
        Completed:"Concluido",
        PostNewJob:"Postar um novo trabalho",
        Payment:"pagamento",
        EnterTitle:"Por favor, digite o título.",
        EnterCategory:"Por favor, selecione categoria.",
        EnterStartDate:"Por favor, selecione a data de início.",
        EnterEndDate:"Por favor, selecione a data final.",
        EnterMinBudget:"Por favor, insira o orçamento mínimo.",
        EnterDesc:"Por favor, digite a descrição do trabalho.",
        PostJob:"Postar um trabalho",
        Done:"terminado",
        JobTitle:"cargo",
        MinPriceUsd:"Preço min (USD)",
        MaxPriceUsd:"Preço máximo (USD)",
        PrivacyPolicy:"Política de Privacidade",
        Edit:"editar",
        Delete:"Apague",
        Reviews:"Opiniões",
        Upcoming:"próximo",
        CurrentlyIn:"Atualmente em",
        Skills:"Habilidades",
        UpdateSkills:"Atualize suas habilidades",
        SubmittedDocs:"Documentos enviados",
        Choose:"escolhe",
        SupportedDocPDF:"O formato de documento suportado é apenas pdf",
        UpdateYourDocs:"Atualize seus documentos",
        EnterFeedback:"Por favor, digite seu feedback",
        Feedback:"realimentação",
        WriteFeedback:"Escrever feedback",
        EnterCodeReceived:"Digite o código que recebeu por e-mail.",
        Search:"Procurar",
        ChangeAppLang:"Alterar linguagem do aplicativo",
        TermsConditions:"Termos e Condições",
        Category:"categoria",
        SelectOneParam:"Selecione pelo menos um parâmetro",
        NoJobFound:"Nenhum trabalho encontrado para os parâmetros determinados",
        Address:"Endereco",
        FailedToRetriveProfile:"Falha ao recuperar detalhes do perfil",
        DocsUploaded:"Documentos carregados com sucesso",
        DocsUploadedFailed:"Falha ao carregar documentos",
        Current:"atual",
        Document1:"Documento1",
        Document2:"Documento2",
        Document3:"Documento3",
        SelectQueryType:"Selecione o tipo de consulta",
        QueryText:"Por favor, digite algumas palavras sobre sua consulta",
        QuerySubmitted:"Recebemos sua consulta, nosso membro da equipe de suporte chegará até você em breve.",
        ContactUs:"Contacte-nos",
        EnterQuery:"Digite sua consulta",
        GeneralQuery:'Consulta Geral',
        Dispute:'disputa',
        PaymentIssue:'Emissão de pagamento',
        Other:'Outros',
        AnyTaskToPost:'Você tem alguma tarefa para postar?',
        TermsPrivacy:"Eu concordo com o JobLamp",
        AcceptTermsPrivacy:"Por favor, aceite Termos e Condições e Política de Privacidade",
        AppliedForJob:"Você se inscreveu com sucesso para o trabalho",
        AboutJobLamp:'Ajudamos você a encontrar um profissional para fazer qualquer trabalho. Estamos disponíveis em todo o mundo, multilingue. Oferecemos prêmios de loteria mensais em dinheiro para te fazer feliz. Job Lamp tem profissionais em muitas áreas como TI, design de computador, desc jobs para reparo e construção, serviços de correio, limpeza e manutenção, eventos e promoções, reparo e instalação de máquinas, assistência jurídica, pet sitting e muitos mais.Oferecemos aos profissionais a oportunidade de explorar suas habilidades em todo o mundo e prestamos serviços aos responsáveis pela realização de seus trabalhos por um profissional de sua escolha.',
        AboutLotto:'Oferecemos prêmios de loteria mensais aos assinantes de nossas contas Básica e VIP para torná-los felizes em trabalhar conosco. Oferecemos 15 prêmios de loteria todos os meses. 1º lugar 300 USD (1 vencedor), 2º lugar 75 USD (4 vencedores), 3º lugar 20 USD (10 vencedores). Oferecemos prêmios trimestrais de US $ 500 para nossos assinantes VIP. Nossa loteria anual para clientes VIP incluirá um primeiro lugar de prêmio de um carro novo entregue em sua porta. Nossa loteria anual para titulares de conta básica incluirá 4 primeiros lugares de prêmio de uma scooter eletrônica entregue em sua porta. O sorteio será transmitido ao vivo em nosso canal do YouTube e será 100% aleatório, sem preconceitos. Seja um membro inscrito e tenha uma oportunidade para ganhar prêmios de loteria mensais.',
        NoJobFound:'Nenhum emprego encontrado',
        Subscriptions:'Assinaturas',
        VisitWeb:'Visite o nosso site',
        FreeAccount:'Conta gratis',
        FeaturesOf:'Características de',
        SubFeatures:'Sem vagas gratuitas para se candidatar \nPagar por candidatura',
        month:'montmêsh',
        year:'ano',
        BasicAccount:'Conta Básica',
        FeaturesBasic:'Você pode se inscrever em até 15 empregos gratuitamente \ nPagar 2 dólares por trabalho após 15 inscrições de empregos \ nVocê pode se inscrever para prêmios de loteria mensais \ nUpload de até 3 carteiras \ nEscolha até 3 categorias \ nEscolha até 3 habilidades',
        VipAccount:'Conta VIP',
        FeatureVIP:'Pode se inscrever para empregos ilimitados \ nPor padrão, elegível para prêmios de loteria mensais \ nPode se inscrever para colocar seu perfil no topo \ nUpload de até 10 carteiras \ nEscolha qualquer número de categorias \ nEscolha qualquer número de habilidades',
        Skip:'Pular',
        BirthDate:'Data de nascimento',
        ChooseBirthDate:'Escolha a data de nascimento',
        ViewPortFolio:'Ver portfólio',
        PortFolio:'Portfólio',
        UploadPortfolio:'Carregar portfólio',
        ClickButton:'Clique no botão abaixo para fazer o upload',
        NoPortFolio:'Você ainda não tem nenhum portfólio',
        Title:'Título',
        ChooseType:'Escolha o tipo',
        MaxPhotoFileSize:'Faça upload da foto com tamanho de até 5 MB',
        MaxVideoFileSize:"Envie um vídeo com um tamanho de até 30 MB",
        ChoosePhoto:'Escolher Foto',
        ChooseVideo:'Escolha o vídeo',
        AddLink:'Adicionar Link',
        UpdateCategories:'Categorias de atualização',
        UpgradePlanForSkill:'Você não pode escolher mais habilidades. Atualize para o plano VIP para escolher habilidades ilimitadas',
        UpgradePlanForCategories:'Você não pode escolher mais categorias. Faça upgrade para o plano VIP para escolher categorias ilimitadas',
        FreeAccountHolderPortFolio:'Como titular de uma conta gratuita, você não pode enviar nenhum portfólio',
        BasicAccountHolderPortFolio:'Como titular de conta básico, você pode fazer upload de até 3 portfólios',
        VIPAccountHolderPortFolio:'Como titular de uma conta VIP, você pode fazer upload de até 10 portfólios',
        WithdrawalAmount:'Por favor, insira o valor para sacar',
        WithdrawalRequest:'Pedido de retirada',
        Amount:'Quantia',
        SubscribeLine:'Clique no botão de assinatura dos planos de assinatura mencionados abaixo para qualquer um deles.',
        Subscribe:'Se inscrever',
        SelectMonthlyYearly:'Selecione a duração da assinatura mensal ou anual'
    },
    ru:{
        AppName:"JobLamp",
        Login:"Авторизоваться",
        SIGNUP:"ЗАРЕГИСТРИРОВАТЬСЯ",
        EmailAddress:"Адрес электронной почты",
        Password:"Пароль",
        ForgotPass:"Забыл пароль?",
        DontHaveAccount:"Нет учетной записи?",
        TopRatedTW:"Рабочие с самым высоким рейтингом",
        EnterValiEmail:"Пожалуйста введите верный адрес электронной почты.",
        EnterPass:"Пожалуйста, введите пароль.",
        EnterFirstName:"Пожалуйста, введите имя.",
        EnterLastName:"Пожалуйста, введите фамилию.",
        EnterMobile:"Пожалуйста, введите номер мобильного телефона.",
        EnterAptmt:"Пожалуйста, введите апартаменты.",
        FirstName:"Имя",
        LastName:"Фамилия",
        MobileNumber:"Номер мобильного телефона",
        EnterStreet:"Пожалуйста, введите название улицы.",
        EnterCountry:"Пожалуйста, выберите Страна.",
        EnterState:"Пожалуйста, выберите государство.",
        EnterCity:"Пожалуйста, выберите город.",
        EnterPincode:"Пожалуйста, введите Pincode.",
        Country:"Страна",
        State:"государство",
        City:"Город",
        TaskGiver:"Дать задачу",
        TaskWorker:"Рабочий-задача",
        RegisterAs:"Зарегистрируйтесь как:",
        SignUp:"Регистрация",
        AlreadyHaveAcc:"У вас уже есть учетная запись?",
        LOGIN:"логин",
        CurrentJobs:"Текущие вакансии",
        AppliedJobs:"Прикладные вакансии",
        CompletedJobd:"Завершенные задания",
        TotalEarnings:"Общий заработок",
        PostedJobs:"Опубликовано Вакансии",
        PastJobs:"Прошлые вакансии",
        ViewByCategory:"Вакансии по категориям",
        ViewAll:"Посмотреть все",
        RecentJobs:"Последние вакансии",
        AboutUs:"О нас",
        ApplicationDetails:"Подробная информация о приложении",
        BidAmount:"Сумма предложения:",
        Hire:"нанимать",
        EnterBiddAmount:"Пожалуйста, введите сумму предложения.",
        EnterCoverText:"Пожалуйста, введите текст Сопроводительного письма.",
        ApplyJob:"Применить работу",
        BiddAmountUSD:"Сумма предложения (USD)",
        CoverLetter:"Сопроводительное письмо",
        Apply:"применять",
        Jobs:"Рабочих мест",
        Categories:"Категории",
        EnterOldPass:"Пожалуйста, введите старый пароль.",
        EnterNewPass:"Пожалуйста, введите новый пароль.",
        PassConfPassNotMatch:"Пароль и подтвердить пароль не совпадают.",
        PassChanged:"Пароль успешно изменился.",
        ResetPass:"Сброс пароля",
        CreateNewPass:"Создание нового пароля",
        PleaseEnterCode:"Пожалуйста, введите код, который был отправлен вам по электронной почте",
        Code:"Код",
        NewPass:"Новый пароль",
        RetypeNewPass:"Повторно ввех новый пароль",
        ChoosePhoto:"Выберите фотографию",
        ChooseFile:"Выберите файл",
        Cancel:"Отмена",
        Chat:"чат",
        Chats:"Чаты",
        EnterDeliveryDetails:"Пожалуйста, введите детали доставки",
        DeliverJob:"Доставка Работа",
        DeliveryNotes:"Заметки о доставке",
        Attachment:"прикрепление",
        Deliver:"доставлять",
        Dashboard:"Панель мониторинга",
        MyJobs:"Моя работа",
        Profile:"профиль",
        Notifications:"Уведомления",
        Settings:"НАСТРОЙКИ",
        Logout:"Выход",
        EditProfile:"Редактировать профиль",
        ApartmentBuilding:"Квартира/Строительство",
        Street:"улица",
        Pincode:"Пин-код",
        AboutMe:"Обо мне",
        Save:"Сохранить",
        EULA:"Лицензионное соглашение с конечных пользователей",
        EnterRegisterEmail:"Введите электронную почту, чтобы получить код сброса пароля",
        Submit:"Послать",
        Contact:"Контактные данные",
        JobApplications:"Заявки на работу",
        JobDetails:"Сведения о работе",
        JobInformation:"Информация о работе",
        JobFrom:"Работа от",
        StartDate:"Дата начала",
        EndDate:"Дата окончания",
        MinPrice:"Мин Прайс",
        MaxPrice:"Макс Прайс",
        Description:"Описание",
        Location:"местоположение",
        FeedBackTW:"Обратная связь для целевого работника",
        FeedbackTG:"Обратная связь для выполнения задач",
        Message:"Сообщение",
        ViewDelivery:"Посмотреть доставку",
        ViewJobApplications:"Просмотр приложений о вакансиях",
        ApplyforJob:"Подать заявление на работу",
        ProvideFeedback:"Обеспечить обратную связь",
        Price:"цена",
        ClearAll:"Очистить все",
        English:"английский",
        Spanish:"испанский",
        French:"французский",
        German:"немецкий",
        Portuguese:"португальский",
        Russian:"русский",
        ChangeLanguage:"Изменение языка",
        Posted:"Опубликовано",
        Applied:"прикладной",
        Active:"активный",
        Delivered:"доставленный",
        ApproveJob:'Утвердить работу',
        RequestModification:'Запросить изменение',
        Past:"прошедший",
        Completed:"завершённый",
        PostNewJob:"Опубликовать новую вакансию",
        Payment:"уплата",
        EnterTitle:"Пожалуйста, введите название.",
        EnterCategory:"Пожалуйста, выберите категорию.",
        EnterStartDate:"Пожалуйста, выберите дату начала.",
        EnterEndDate:"Пожалуйста, выберите дату окончания.",
        EnterMinBudget:"Пожалуйста, введите минимальный бюджет.",
        EnterDesc:"Пожалуйста, введите описание работы.",
        PostJob:"Опубликовать вакансию",
        Done:"Договорились",
        JobTitle:"Название задания",
        MinPriceUsd:"Мин Прайс (USD)",
        MaxPriceUsd:"Максимальная цена (USD)",
        PrivacyPolicy:"Политика конфиденциальности",
        Edit:"Редактировать",
        Delete:"удалить",
        Reviews:"Отзывов",
        Upcoming:"развивающийся",
        CurrentlyIn:"В настоящее время в",
        Skills:"Навыки",
        UpdateSkills:"Обновление навыков",
        SubmittedDocs:"Представленные документы",
        Choose:"выбирать",
        SupportedDocPDF:"Поддерживаемый формат документа является pdf только",
        UpdateYourDocs:"Обновление документов",
        EnterFeedback:"Пожалуйста, введите yoour обратной связи",
        Feedback:"Отзыв",
        WriteFeedback:"Пишите Отзывы",
        EnterCodeReceived:"Пожалуйста, введите код, который вы получили по электронной почте.",
        Search:"Поиск",
        ChangeAppLang:"Изменение языка приложений",
        TermsConditions:"Положения и условия",
        Category:"категория",
        SelectOneParam:"Пожалуйста, выберите по крайней мере один параметр",
        NoJobFound:"Задание по данному параметру не найдено",
        Address:"адрес",
        FailedToRetriveProfile:"Не удалось получить сведения профиля",
        DocsUploaded:"Документы, успешно загруженные",
        DocsUploadedFailed:"Не удалось загрузить документы",
        Current:"Тока",
        Document1:"Документ1",
        Document2:"Документ2",
        Document3:"Документ3",
        SelectQueryType:"Пожалуйста, выберите тип запроса",
        QueryText:"Пожалуйста, введите несколько слов о вашем запросе",
        QuerySubmitted:"Мы получили ваш запрос, наш член группы поддержки скоро до вас дойдет.",
        ContactUs:"Свяжитесь с нами",
        EnterQuery:"Введите свой запрос",
        GeneralQuery:'Общий запрос',
        Dispute:'спор',
        PaymentIssue:'Проблема оплаты',
        Other:'Другое',
        AnyTaskToPost:'Есть ли у вас какие-либо задачи, чтобы получить возможность выдать?',
        TermsPrivacy:"Я согласен с JobLamp в",
        AcceptTermsPrivacy:"Пожалуйста, примите условия и политику конфиденциальности",
        AppliedForJob:"Вы успешно подали заявку на работу",
        AboutJobLamp:'Мы поможем вам найти профессионала для выполнения любой работы. Мы доступны по всему миру, многоязычны. Мы предлагаем ежемесячные денежные призы лотереи, чтобы вы были счастливы. В Job Lamp работают профессионалы во многих областях, таких как ИТ, компьютерный дизайн, выполнение работ по ремонту и строительству, курьерские услуги, уборка и уборка, мероприятия и рекламные акции, ремонт и установка машин, юридическая помощь, присмотр за домашними животными и многое другое.Мы предоставляем профессионалам возможность изучить свои навыки по всему миру и предоставляем услуги ответственным за выполнение работы профессионалами по их выбору.',
        AboutLotto:'Мы предлагаем ежемесячные призы в лотерею нашим подписчикам с базовыми и VIP-аккаунтами, чтобы они были довольны работой с нами. Каждый месяц мы предлагаем 15 лотерейных призов. 1 место 300 долларов США (1 победитель), 2 место 75 долларов США (4 победителя), 3 место 20 долларов США (10 победителей). Мы предлагаем нашим VIP-подписчикам ежеквартальные призы в размере 500 долларов США. Наша годовая лотерея для VIP-клиентов будет включать первое призовое место в виде новенького автомобиля, доставленного к вашей двери. Наша ежегодная лотерея для владельцев базовой учетной записи будет включать в себя 4 первых призовых места электронного скутера, доставленного к вашей двери. Розыгрыш будет транслироваться в прямом эфире на нашем канале YouTube и будет на 100% случайным без предвзятости. Подпишитесь на участника и получите возможность чтобы выиграть ежемесячные призы в лото.',
        NoJobFound:'Вакансий не найдено',
        Subscriptions:'Подписки',
        VisitWeb:'Посетите наш сайт',
        FreeAccount:'Бесплатный аккаунт',
        FeaturesOf:'Особенности',
        SubFeatures:'Нет бесплатных вакансий, на которые можно подать заявку \nПлатить за каждое заявление о приеме на работу',
        month:'месяц',
        year:'год',
        BasicAccount:'Базовая учетная запись',
        FeaturesBasic:'Вы можете бесплатно подать заявку на 15 вакансий \ nПлатите 2 доллара США за вакансию после 15 заявок на вакансию \ nВы можете подать заявку на ежемесячные призы в лотерею \ nЗагрузите до 3 портфолио \ nВыберите до 3 категорий \ nВыберите до 3 навыков',
        VipAccount:'VIP аккаунт',
        FeatureVIP:'Может подавать заявки на неограниченное количество вакансий \ nПо умолчанию имеет право на ежемесячные призы лото \ nМожно подать заявку на размещение своего профиля наверху \ nЗагрузить до 10 портфолио \ nВыберите любое количество категорий \ nВыберите любое количество навыков',
        Skip:'Пропускать',
        BirthDate:'Дата рождения',
        ChooseBirthDate:'Пожалуйста, выберите дату рождения',
        ViewPortFolio:'Посмотреть портфолио',
        PortFolio:'портфолио',
        UploadPortfolio:'Загрузить портфолио',
        ClickButton:'Нажмите кнопку ниже, чтобы загрузить',
        NoPortFolio:'У вас еще нет портфолио',
        Title:'Заголовок',
        ChooseType:'Выберите тип',
        MaxPhotoFileSize:'Пожалуйста, загрузите фото размером не более 5 МБ.',
        MaxVideoFileSize:'Пожалуйста, загрузите видео размером не более 30 МБ',
        ChoosePhoto:'Выбрать фото',
        ChoosePhoto:'Выбрать видео',
        AddLink:'Добавить ссылку',
        UpdateCategories:'Категории обновлений',
        UpgradePlanForSkill:'Больше навыков выбрать нельзя. Перейдите на план VIP, чтобы выбрать неограниченные навыки',
        UpgradePlanForCategories:'Больше категорий выбрать нельзя. Перейдите на план VIP, чтобы выбрать неограниченное количество категорий',
        FreeAccountHolderPortFolio:'Как владелец бесплатного аккаунта вы не можете загружать портфолио',
        BasicAccountHolderPortFolio:'Как владелец базовой учетной записи вы можете загрузить до 3 портфелей.',
        VIPAccountHolderPortFolio:'Как владелец VIP-аккаунта вы можете загрузить до 10 портфелей.',
        WithdrawalAmount:'Пожалуйста, введите сумму для вывода',
        WithdrawalRequest:'Запрос на вывод',
        Amount:'Количество',
        SubscribeLine:'Нажмите кнопку подписки из нижеупомянутых планов подписки на любой из них.',
        Subscribe:'Подписывайся',
        SelectMonthlyYearly:'Пожалуйста, выберите продолжительность подписки: ежемесячно или ежегодно.'
    }
});

export default strings;